import { Octokit } from "octokit";
import type { SimpleGit } from "simple-git";
import type { AnalysisResult, FixResult } from "@/types";

export async function getDefaultBranch(
  accessToken: string,
  owner: string,
  repo: string
): Promise<string> {
  const octokit = new Octokit({ auth: accessToken });
  const { data } = await octokit.rest.repos.get({ owner, repo });
  return data.default_branch;
}

export async function pushBranchAndCreatePr(params: {
  git: SimpleGit;
  cloneDir: string;
  accessToken: string;
  owner: string;
  repo: string;
  fixes: FixResult[];
  analysis: AnalysisResult;
  targetLocale: string;
  fixModes: { seo: boolean; aria: boolean; fullPage: boolean };
}) {
  const { git, accessToken, owner, repo, fixes, analysis, targetLocale, fixModes } = params;

  // Branch name: lingoseo/{locale}-{modes}
  // e.g. lingoseo/es-MX-seo-aria, lingoseo/ar-full, lingoseo/ja-seo
  const modeSlug = [
    fixModes.seo && "seo",
    fixModes.aria && "aria",
    fixModes.fullPage && "full",
  ].filter(Boolean).join("-");

  const branchName = `lingoseo/${targetLocale}-${modeSlug}`;
  const defaultBranch = await getDefaultBranch(accessToken, owner, repo);

  const modeLabel = [
    fixModes.seo && "SEO metadata",
    fixModes.aria && "ARIA accessibility",
    fixModes.fullPage && "full page content",
  ].filter(Boolean).join(", ");

  // Create branch and commit
  await git.checkoutLocalBranch(branchName);
  await git.add(".");
  await git.commit(
    `fix(seo): ${targetLocale} — ${modeLabel} by LingoSEO\n\nPowered by lingo.dev SDK + Gemini — fixed ${analysis.issues.length} issues across ${fixes.length} files\nLocale: ${targetLocale} | Modes: ${modeLabel}`
  );
  await git.push("origin", branchName, ["--set-upstream"]);

  // Create PR
  const octokit = new Octokit({ auth: accessToken });
  const body = generatePrBody(analysis, fixes, targetLocale, fixModes);

  const { data: pr } = await octokit.rest.pulls.create({
    owner,
    repo,
    head: branchName,
    base: defaultBranch,
    title: `fix(seo): ${targetLocale} — ${modeLabel} [LingoSEO]`,
    body,
  });

  return {
    prUrl: pr.html_url,
    prNumber: pr.number,
    branchName,
    filesChanged: fixes.length,
  };
}

function generatePrBody(
  analysis: AnalysisResult,
  fixes: FixResult[],
  targetLocale: string,
  fixModes: { seo: boolean; aria: boolean; fullPage: boolean }
): string {
  const critical = analysis.summary.critical || 0;
  const warning = analysis.summary.warning || 0;
  const info = analysis.summary.info || 0;

  const modeLabel = [
    fixModes.seo && "SEO Metadata",
    fixModes.aria && "ARIA Accessibility",
    fixModes.fullPage && "Full Page Content",
  ].filter(Boolean).join(" + ");

  let body = `## LingoSEO — ${targetLocale} · ${modeLabel}\n\n`;
  body += `Automated fixes generated by [LingoSEO](https://github.com) using **lingo.dev SDK** + **Gemini** (culturally accurate, market-specific SEO keywords).\n\n`;
  body += `| | |\n|---|---|\n`;
  body += `| **Target locale** | \`${targetLocale}\` |\n`;
  body += `| **Modes applied** | ${modeLabel} |\n`;
  body += `| **Translation engine** | lingo.dev SDK + Gemini |\n\n`;
  body += `### Scan Summary\n`;
  body += `| Severity | Count |\n|----------|-------|\n`;
  body += `| Critical | ${critical} |\n`;
  body += `| Warning | ${warning} |\n`;
  body += `| Info | ${info} |\n\n`;
  body += `**Files scanned:** ${analysis.scannedFiles}\n`;
  body += `**Files modified:** ${fixes.filter(f => f.filePath !== "__fixer_log__").length}\n\n`;

  body += `### Issues Fixed\n`;
  for (const issue of analysis.issues.slice(0, 20)) {
    body += `- **${issue.type}** (${issue.severity}) in \`${issue.filePath}\`: ${issue.message}\n`;
  }
  if (analysis.issues.length > 20) {
    body += `\n...and ${analysis.issues.length - 20} more issues\n`;
  }

  body += `\n---\n`;
  body += `> Powered by [lingo.dev](https://lingo.dev) SDK + LingoSEO\n`;

  return body;
}
