import { Octokit } from "octokit";
import type { SimpleGit } from "simple-git";
import type { AnalysisResult, FixResult } from "@/types";

export async function getDefaultBranch(
  accessToken: string,
  owner: string,
  repo: string
): Promise<string> {
  const octokit = new Octokit({ auth: accessToken });
  const { data } = await octokit.rest.repos.get({ owner, repo });
  return data.default_branch;
}

export async function pushBranchAndCreatePr(params: {
  git: SimpleGit;
  cloneDir: string;
  accessToken: string;
  owner: string;
  repo: string;
  fixes: FixResult[];
  analysis: AnalysisResult;
}) {
  const { git, accessToken, owner, repo, fixes, analysis } = params;

  const branchName = `lingoseo/seo-optimize-${Date.now()}`;
  const defaultBranch = await getDefaultBranch(accessToken, owner, repo);

  // Create branch and commit
  await git.checkoutLocalBranch(branchName);
  await git.add(".");
  await git.commit(
    `fix(seo): multilingual SEO optimizations by LingoSEO\n\nPowered by lingo.dev SDK — translated ${analysis.issues.length} SEO issues across ${fixes.length} files`
  );
  await git.push("origin", branchName, ["--set-upstream"]);

  // Create PR
  const octokit = new Octokit({ auth: accessToken });
  const body = generatePrBody(analysis, fixes);

  const { data: pr } = await octokit.rest.pulls.create({
    owner,
    repo,
    head: branchName,
    base: defaultBranch,
    title: `fix(seo): Multilingual SEO optimizations by LingoSEO`,
    body,
  });

  return {
    prUrl: pr.html_url,
    prNumber: pr.number,
    branchName,
    filesChanged: fixes.length,
  };
}

function generatePrBody(
  analysis: AnalysisResult,
  fixes: FixResult[]
): string {
  const critical = analysis.summary.critical || 0;
  const warning = analysis.summary.warning || 0;
  const info = analysis.summary.info || 0;

  let body = `## LingoSEO — Multilingual SEO Optimization\n\n`;
  body += `Automated SEO fixes generated by [LingoSEO](https://github.com) using **lingo.dev SDK** for translations.\n\n`;
  body += `### Summary\n`;
  body += `| Severity | Count |\n|----------|-------|\n`;
  body += `| Critical | ${critical} |\n`;
  body += `| Warning | ${warning} |\n`;
  body += `| Info | ${info} |\n\n`;
  body += `**Files scanned:** ${analysis.scannedFiles}\n`;
  body += `**Files modified:** ${fixes.length}\n`;
  body += `**Locales detected:** ${analysis.localesDetected.join(", ") || "none"}\n\n`;

  body += `### Issues Fixed\n`;
  for (const issue of analysis.issues.slice(0, 20)) {
    body += `- **${issue.type}** (${issue.severity}) in \`${issue.filePath}\`: ${issue.message}\n`;
  }
  if (analysis.issues.length > 20) {
    body += `\n...and ${analysis.issues.length - 20} more issues\n`;
  }

  body += `\n---\n`;
  body += `> Powered by [lingo.dev](https://lingo.dev) SDK + LingoSEO\n`;

  return body;
}
